# Generated by Django 4.0.3 on 2023-04-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('dept', models.CharField(max_length=500)),
                ('clgname', models.CharField(max_length=500)),
            ],
        ),
    ]
